name: Complete workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      # this step download all codebase with git history

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # this step install node.js

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      # this step install mondodb to run integration tests

      - name: Install dependencies
        run: yarn --frozen-lockfile
      # this step install dependencies, --frozen-lockfile block yarn to update versions

      - name: Run all tests
        run: yarn test

        # - shell: bash
        #   if: github.ref == 'refs/heads/master'
        # in umbler with ssh
        # name: Create SSH deploymeny key
        # env:
        #   SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # run: ./scripts/deploy.sh

        # Deployment with heroku action
        - shell: bash
          if: github.ref == 'refs/heads/master'
          name: Deployment
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          CI: true
