
name: Complete workflow

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
			matrix:
				node-version: [14.x]
				mongodb-version: [4.2]

		steps:
		- uses: actions/checkout@v2
		- run: git fetch --prune --unshallow
		# this step download all codebase with git history

		- name: Use Node.js ${{ matrix.node-version } }
			uses: actions/setup-node@v1
			with:
				node-version: ${{ matrix.node-version }}
		# this step install node.js

		- name: Start MongoDB
			uses: supercharge/mongodb-github-action@1.1.0
			with:
				mongodb-version: ${{ mongodb-version }}
		# this step install mondodb to run integration tests

		- name: Install dependencies
			run: yarn --frozen-lockfile
		# this step install dependencies, --frozen-lockfile block yarn to update versions

		- name: Run all tests
			run: yarn test
